netcdf_data:
  ocean:
    data: data/field_netcdfs/hfr_2023_03_new.nc
    # datasource: pyplume.thredds_data.SRC_THREDDS_HYCOM
    allow_time_extrapolation: true
    time_range: [2023-03-03T03, 2023-03-03T15]
    gapfill_steps:
      - path: pyplume.gapfilling.LowResOversample
        args:
          references: [data/field_netcdfs/FMRC_GLBy0.08_930_FMRC_best (1)_modified.nc]
      # - path: pyplume.gapfilling.DCTPLS
      #   args:
      #     exclude_oob: false
  wind:
    path: data/mets1.mat
    ratio: 0.03
    add_to_field_directly: true
parcels_config:
  save_dir: results
  particle_type: pyplume.kernels.ThreddsParticle
  kernels:
    - parcels.AdvectionRK4
  time_range: [2023-03-03T03, 2023-03-03T15]
  repeat_dt: 3600
  repetitions: -1
  instances_per_spawn: 1
  spawn_points:
    - label: release
      point: [6.95, 134.15]
      pattern:
        type: grid
        args:
          size: 3
          gapsize: 0.01
  simulation_dt: 600
  snapshot_interval: 1800
postprocess_config: {}
save_snapshots: true
plotting_config:
  # draw_coasts: true
  plot_features:
    - path: pyplume.plot_features.NanSeparatedFeature
      label: coastline
      args:
        data: data/palaucoastline1.mat
        color: k
    # - path: pyplume.plot_features.WindVectorFeature
    #   label: windcompass
    #   args:
    #     data
