netcdf_data:
  ocean:
    data: USEC_6KM_HOURLY
    datasource: pyplume.thredds_data.SRC_THREDDS_HFRNET_UCSD
    domain:
      # rough estimate of available HFRNet data near New York
      # southwest: 38.162201, -75.709632
      # northeast: 41.520008, -69.723751
      S: 38.162201
      N: 41.520008
      W: -75.709632
      E: -69.723751
    time_range:
      # hurrican henri timespan (cat 1 hurricane/tropical storm near new york)
      - 2021-08-21T12:00
      - 2021-08-23T18:00
    boundary_condition: freeslip
parcels_config:
  save_dir: results
  particle_type: pyplume.kernels.ThreddsParticle
  kernels:
    - parcels.AdvectionRK4
    - pyplume.kernels.AgeParticle
    - pyplume.kernels.RandomWalk
  time_range:
    - 2021-08-21T12:00
    - 2021-08-23T18:00
  repeat_dt: 3600
  repetitions: -1
  instances_per_spawn: 1
  spawn_points:
    -
      label: apoint
      point: [40.3992, -73.6665]
      release: 2021-08-21T12:00
      pattern: {
        "type": "grid",
        "args": {
          "size": 3,
          "gapsize": 0.1
        }
      }
  simulation_dt: 600
  snapshot_interval: 1800
postprocess_config: {}
save_snapshots: true
plotting_config:
  shown_domain:
    S: 38.162201
    N: 41.520008
    W: -75.709632
    E: -69.723751
  draw_coasts: true
