netcdf_data:
  ocean:
    data: data/field_netcdfs/cmems_mod_glo_phy_anfc_merged-uv_PT1H-i_1677893029445_modified.nc
    allow_time_extrapolation: true
    time_range: [2023-03-03T03, 2023-03-06T23]
    # gapfill_steps:
      # DCT-PLS gapfilling. It's very aggressive on smoothing.
      # - path: pyplume.gapfilling.DCTPLS
      #   args:
      #     exclude_oob: false
  wind:
    path: data/winds1.mat
    ratio: 0.03
    add_to_field_directly: true
parcels_config:
  save_dir: results
  particle_type: pyplume.kernels.ThreddsParticle
  kernels:
    - parcels.AdvectionRK4
    - pyplume.kernels.RandomWalk5cm
  time_range: [2023-03-03T03, 2023-03-06T23]
  repeat_dt: 3600
  repetitions: 3
  instances_per_spawn: 1
  spawn_points:
    - label: release
      point: [6.95, 134.15]
      pattern:
        type: grid
        args:
          size: 15
          gapsize: 0.005
  simulation_dt: 600
  snapshot_interval: 1800
postprocess_config: {}
save_snapshots: true
plotting_config:
  # draw_coasts: true
  plot_features:
    - path: pyplume.plot_features.NanSeparatedFeature
      label: coastline
      args:
        data: data/palaucoastline1.mat
        color: k
