netcdf_data:
  ocean:
    path: data/field_netcdfs/tj_plume_1km_2022-09.nc
    gapfill_steps:
      - path: pyplume.gapfilling.InterpolationStep
        args:
          references:
            - USWC_2KM_HOURLY
            - USWC_6KM_HOURLY
      - path: pyplume.gapfilling.SmoothnStep
        args:
          mask: data/field_netcdfs/tj_plume_1km_2022-09_mask.npy
  alongshore: data/field_netcdfs/tj_plume_alongshore_2022-09.nc
parcels_config:
  save_dir: results
  particle_type: pyplume.kernels.ThreddsParticle
  kernels:
    - pyplume.kernels.AdvectionRK4BorderCheck
    - pyplume.kernels.AgeParticle
    - pyplume.kernels.RandomWalk
  time_range:
    # Hurricane Kay timespan
    - 2022-09-08T06:00
    - 2022-09-12T00:00
  repeat_dt: 3600
  repetitions: -1
  instances_per_spawn: 1
  spawn_points: data/spawn_points_mats/glist90zj_pts_position_spawn.mat
  simulation_dt: 300
  snapshot_interval: 3600
postprocess_config: {}
save_snapshots: true
plotting_config:
  shown_domain:
    S: 32.525
    N: 32.7
    W: -117.27
    E: -117.09
  draw_coasts: false
  plot_features:
    - path: pyplume.plot_features.NanSeparatedFeature
      label: coastline
      args:
        path: data/coastOR2Mex_tijuana.mat
        color: k
    - path: pyplume.plot_features.StationFeature
      label: station
      args:
        path: data/wq_stposition.mat
        labels:
          - Coronado (North Island)
          - Silver Strand
          - Silver Strand Beach
          - Carnation Ave.
          - Imperial Beach Pier
          - Cortez Ave.
          - End of Seacoast Dr.
          - 3/4 mi. N. of TJ River Mouth
          - Tijuana River Mouth
          - Monument Rd.
          - Board Fence
          - Mexico
        track_dist: 1000
    - path: pyplume.plot_features.NearcoastDensityFeature
      label: nearcoast_density
      args:
        origin:
          - 32.556772435531
          - -117.13016494831
        stations: data/wq_stposition.mat
        coastline: data/coastline.mat
        xlim:
          - -16
          - 4
        ymax: 1
        track_dist: 900
